<?php
/**
 * Helper classes for PrestaShop CMS.
 *
 * @author    Maksim T. <zapalm@yandex.com>
 * @copyright 2018 Maksim T.
 * @license   https://opensource.org/licenses/MIT MIT
 * @link      https://github.com/zapalm/prestashopHelpers GitHub
 * @link      https://prestashop.modulez.ru/en/tools-scripts/53-helper-classes-for-prestashop.html Homepage
 */

namespace zapalm\prestashopHelpers\helpers;

/**
 * UTM label helper.
 *
 * @version 0.1.0
 *
 * @link https://effinamazing.com/blog/dummies-guide-utm-tracking/ Description in English.
 * @link http://convert.ua/blog/ppc/utm-parameters/ Description in Russian.
 *
 * @author Maksim T. <zapalm@yandex.com>
 */
class UtmLabelHelper
{
    const PARAM_UTM_SOURCE   = 'utm_source';
    const PARAM_UTM_MEDIUM   = 'utm_medium';
    const PARAM_UTM_CAMPAIGN = 'utm_campaign';
    const PARAM_UTM_CONTENT  = 'utm_content';
    const PARAM_UTM_TERM     = 'utm_term';
    const PARAM_UTM_REFERRER = 'utm_referrer';

    /**
     * Returns UTM labels that are generated by specified params.
     *
     * @param string      $source   The source or the referrer (e.g. google, newsletter).
     * @param string      $medium   The marketing medium (e.g. cpc, banner, email).
     * @param string|null $campaign The campaign name, for example, a product, a promo code, or a slogan (e.g. spring_sale).
     * @param string|null $content  The campaign content (use to differentiate ads).
     * @param string|null $term     The campaign term to identify the paid keywords.
     * @param string|null $referrer The extra referrer. This is the additional parameter to allow Yandex.Metrica (may be also others) to correctly detect the source of a click-through when there is a JavaScript redirect, or when users navigate to your site over the HTTP protocol from a site that is only available over HTTPS.
     *
     * @return string[] The array of UTM labels associated with their values.
     *
     * @author Maksim T. <zapalm@yandex.com>
     */
    public static function getLabels($source, $medium, $campaign = null, $content = null, $term = null, $referrer = null)
    {
        return array_filter([
            static::PARAM_UTM_SOURCE   => $source,
            static::PARAM_UTM_MEDIUM   => $medium,
            static::PARAM_UTM_CAMPAIGN => $campaign,
            static::PARAM_UTM_CONTENT  => $content,
            static::PARAM_UTM_TERM     => $term,
            static::PARAM_UTM_REFERRER => $referrer,
        ]);
    }
}