<?php
/**
 * Helper classes for PrestaShop CMS.
 *
 * @author    Maksim T. <zapalm@yandex.com>
 * @copyright 2018 Maksim T.
 * @license   https://opensource.org/licenses/MIT MIT
 * @link      https://github.com/zapalm/prestashopHelpers GitHub
 * @link      https://prestashop.modulez.ru/en/tools-scripts/53-helper-classes-for-prestashop.html Homepage
 */

namespace zapalm\prestashopHelpers\helpers;

/**
 * UTM helper.
 *
 * @version 0.1.0
 *
 * @link https://effinamazing.com/blog/dummies-guide-utm-tracking/ Description in English.
 * @link http://convert.ua/blog/ppc/utm-parameters/ Description in Russian.
 *
 * @author Maksim T. <zapalm@yandex.com>
 */
class UtmLabelsHelper
{
    const PARAM_UTM_SOURCE   = 'utm_source';
    const PARAM_UTM_MEDIUM   = 'utm_medium';
    const PARAM_UTM_CAMPAIGN = 'utm_campaign';
    const PARAM_UTM_CONTENT  = 'utm_content';
    const PARAM_UTM_TERM     = 'utm_term';

    /**
     * Returns UTM labels that are generated by specified params.
     *
     * @param string      $source   Source.
     * @param string      $medium   Medium.
     * @param string      $campaign Campaign.
     * @param string|null $content  Content.
     * @param string|null $term     Term.
     *
     * @return string[] The array of UTM labels associated with their values.
     *
     * @author Maksim T. <zapalm@yandex.com>
     */
    public static function getLabels($source, $medium, $campaign, $content = null, $term = null)
    {
        return array_filter([
            static::PARAM_UTM_SOURCE   => $source,
            static::PARAM_UTM_MEDIUM   => $medium,
            static::PARAM_UTM_CAMPAIGN => $campaign,
            static::PARAM_UTM_CONTENT  => $content,
            static::PARAM_UTM_TERM     => $term,
        ]);
    }
}